/*Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter at a random position.

Find the letter that was added in t.

Example:

Input:
s = "abcd"
t = "abcde"

Output:
e

Explanation:
'e' is the letter that was added.*/

class Solution {
    public char findTheDifference(String s, String t) {
        int[] sa = new int[26];
        if(s == null || t == null)
            return 'a';
        for(char c : t.toCharArray()) {
            sa[c-'a']++;
        }
        for(char c : s.toCharArray()) {
            sa[c-'a']--;
        }
        for(int i = 0; i < sa.length; i++) {
            if(sa[i] > 0)
                return (char)(i+'a');
        }
        return 'a';
    }
}