/*
You are given two strings s and t.
String t is generated by random shuffling string s and then add one more letter at a random position.
Return the letter that was added to t.

Example 1:
Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.

Example 2:
Input: s = "", t = "y"
Output: "y"

Constraints:
0 <= s.length <= 1000
t.length == s.length + 1
s and t consist of lowercase English letters.
*/

class Solution {
    public char findTheDifference(String s, String t) {
        int[] res = new int[26];
        int pos = 0;
        for(int i = 0; i < t.length(); i++) {
            res[t.charAt(i) - 'a']++;
        }
        for(int i = 0; i < s.length(); i++) {
            res[s.charAt(i) - 'a']--;
        }
        for(int i = 0; i < res.length; i++) {
            if(res[i] == 1) {
                pos = i;
            }
        }
        return (char) (pos + 'a');
    }
}